// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MusicList() {
  return window['go']['api']['App']['MusicList']();
}

export function MusicScan() {
  return window['go']['api']['App']['MusicScan']();
}
